TEXFILE="main.tex"

all: pdf clean

pdf:
	pdflatex -output-directory=out $(TEXFILE)
	# pdflatex -output-directory=out $(TEXFILE)
	# pdflatex -output-directory=out $(TEXFILE)

clean:
	rm out/*.aux out/*.log

# make TEXFILE=""
